# Generated by Django 3.1.1 on 2020-10-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_auto_20201014_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='main_cat',
            field=models.ManyToManyField(max_length=200, null=True, to='Store.MainCategory'),
        ),
    ]
