# Generated by Django 3.1.1 on 2020-10-14 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_category_main_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mcat',
        ),
    ]
