# Generated by Django 3.1.1 on 2020-10-14 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_remove_product_mcat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='main_cat',
        ),
        migrations.AddField(
            model_name='category',
            name='main_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.maincategory'),
        ),
    ]
